name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Clang
        run: sudo apt-get update && sudo apt-get install -y clang

      - name: Build
        run: make

      - name: Run Tests
        run: ./test_cVec 
